task default: %w[test]

task :test do
  ruby "solution.rb"
  sh "rspec extended_spec.rb --require ./solution.rb --colour --format documentation"
  sh "skeptic --lines-per-method 10 --line-length 80 --max-nesting-depth 2 --methods-per-class 16 --no-semicolons --no-trailing-whitespace --check-syntax --no-global-variables --naming-conventions --max-method-arity 4 --spaces-around-operators solution.rb"
end
