#!/bin/bash

echo "Testing..."
rspec snake_spec.rb -r ./snake.rb -c -f documentation

echo "Skeptic:"
skeptic --lines-per-method 8 --line-length 80 --max-nesting-depth 1 --methods-per-class 10 --no-semicolons --no-trailing-whitespace --check-syntax --no-global-variables --english-words-for-names='xs ys' --naming-conventions snake.rb
